feat: Add three dot menu to the post
raisethevoice/raisethevoice pull request #50
Opened 2024-08-17 13:32 UTC by arifjahan88

2024-08-17 14:40 UTC, shahmedme commented
We can add some functionalities on dropdown too. These can be added,
- Edit post
- Delete post
- Report post

More suggestions are appreciated.

2024-08-18 09:34 UTC, arifjahan88 commented
@shahmedme Added dropdown menu. #15
![image](https://github.com/user-attachments/assets/394273a3-5a09-422f-b232-404d911e9fcd)

2024-08-26 05:14 UTC, arifjahan88 commented
@shahmedme vai edit and deleteModal added. olease check #15 

![image](https://github.com/user-attachments/assets/417c5527-42d5-4327-8f52-fc2968209bed)
![image](https://github.com/user-attachments/assets/5977addc-5781-404e-9aca-4f3626e83e3d)

2024-08-26 13:51 UTC, shahmedme commented
Thanks for the PR. It's a nice addition. Here're some feedbacks:

- Only post owner can use only Edit and Delete action.
- Only other users can use Report post action.
- Need to add API connection too for Edit and Delete post.
- Can we make modal size (width, height) same as create post modal?
- Let's have a gray background while hovering over three dot button.
- Also we can place delete post confirmation modal vertically centered.

2024-08-26 14:01 UTC, shahmedme requested changes
Thanks for the PR. It's a nice addition. Here're some feedbacks:

- Only post owner can use only Edit and Delete action.
- Only other users can use Report post action.
- Need to add API connection too for Edit and Delete post.
- Can we make modal size (width, height) same as create post modal?
- Let's have a gray background while hovering over three dot button.
- Also we can place delete post confirmation modal vertically centered.

2024-08-26 14:01 UTC, shahmedme commented on web/src/pages/feed/views/Feed/PostSingle.tsx
> +      dispatch(handleDeletePostModal({ open: true, id: id }));
For delete we can use Modal.confirm() from antd

2024-08-26 14:01 UTC, shahmedme commented on web/src/pages/feed/views/Feed/PostSingle.tsx
> +            <BsThreeDotsVertical className="text-xs text-neutral-500 cursor-pointer" />
Can we put gray background while hover?

2024-08-26 16:53 UTC, arifjahan88 commented on web/src/pages/feed/views/Feed/PostSingle.tsx
> +            <BsThreeDotsVertical className="text-xs text-neutral-500 cursor-pointer" />
added

2024-08-26 16:54 UTC, arifjahan88 commented on web/src/pages/feed/views/Feed/PostSingle.tsx
> +  const handlethreeDotsClick = (key: string) => {
done

2024-09-02 13:31 UTC, closed without merging