Add three dot menu to the post [ Report post ]
raisethevoice/raisethevoice pull request #71
Opened 2024-09-05 07:35 UTC by anikakash

**Bug Fix:**
1. Authorized users can now update or delete only their own posts.

**New Feature:**
1. Implemented a reporting system for posts by other users.

2024-09-05 10:54 UTC, anikakash reviewed
Review done from my side

2024-09-05 13:47 UTC, srijonashraf requested changes

2024-09-05 13:47 UTC, srijonashraf commented on server/feed/serializers.py
> +            raise serializers.ValidationError("You cannot report your own post.")
validation could be handled from View

2024-09-05 17:41 UTC, anikakash commented on server/feed/serializers.py
> +            raise serializers.ValidationError("You cannot report your own post.")
done

2024-09-07 21:03 UTC, anikakash reviewed
made request review changes.

2024-09-16 15:19 UTC, srijonashraf approved these changes
Approved

2024-09-20 12:07 UTC, merged